In [76]:

import numpy as np
import pandas as pd

import sklearn

In [77]:
a = np.random.randint(10,size=(5,4))

In [49]:
a

array([[1, 5, 3, 7],
       [3, 0, 5, 2],
       [2, 9, 2, 6],
       [6, 7, 7, 4],
       [1, 1, 9, 2]])

In [86]:
np.linalg.eig(np.diag([1,2,3]))

(array([1., 2., 3.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [83]:
m

array([1., 2., 3.])

In [84]:
m

array([1., 2., 3.])

In [85]:
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
a = np.array([2,3,3,-6]).reshape(2,2,order = 'F')

In [89]:
a

array([[ 2,  3],
       [ 3, -6]])

In [90]:
np.linalg.eig(a)

(array([ 3., -7.]), array([[ 0.9486833 , -0.31622777],
        [ 0.31622777,  0.9486833 ]]))

In [91]:
np.linalg.det(a)

-21.0

In [92]:
a = np.array([0.95,0.05,0.03,0.97]).reshape(2,2,order='f')

In [93]:
a

array([[0.95, 0.03],
       [0.05, 0.97]])

In [94]:
np.linalg.eig(a)

(array([0.92, 1.  ]), array([[-0.70710678, -0.51449576],
        [ 0.70710678, -0.85749293]]))

In [95]:
a-1

array([[-0.05, -0.97],
       [-0.95, -0.03]])

In [96]:
import sympy

ModuleNotFoundError: No module named 'sympy'

In [97]:
a = np.array([6,-2,-1,-2,6,-1,-1,-1,5]).reshape(3,3,order='f')

In [98]:

a

array([[ 6, -2, -1],
       [-2,  6, -1],
       [-1, -1,  5]])

In [99]:
m,n = np.linalg.eig(a)

In [100]:
m

array([3., 8., 6.])

In [101]:
a = np.array([7,-4,2,1]).reshape(2,2,order ='f')

In [102]:
a

array([[ 7,  2],
       [-4,  1]])

In [104]:
m,n = np.linalg.eig(a)

In [105]:
n

array([[ 0.70710678, -0.4472136 ],
       [-0.70710678,  0.89442719]])

In [107]:
m

array([5., 3.])

In [109]:
a = np.array([1,-1,-1,2]).reshape(2,2,order='f')

In [110]:
a

array([[ 1, -1],
       [-1,  2]])

In [111]:
np.linalg.inv(a)

array([[2., 1.],
       [1., 1.]])