In [32]:
import numpy as np
import pandas as pd


In [76]:
data =  pd.read_csv('testSet.csv',header = None)

data = data.values

datamat = np.mat(data[:,0:2])

labelmat = np.mat(data[:,2:])

m,n = datamat.shape

alphas = np.mat(np.zeros((m,1)))

k = np.mat(np.zeros((m,m)))

a = np.mat(np.random.randint(3,size=(5,2)))



In [105]:
k = np.dot(datamat, datamat.T)

In [54]:
k.shape

(100, 100)

In [56]:
k1[0:3,0:3]

matrix([[ 16.45930283,  15.74944568,  23.62676274],
        [ 15.74944568,  15.64899582,  18.75800936],
        [ 23.62676274,  18.75800936,  59.52179808]])

In [64]:
for i in range(m):
    k[:,i] = np.dot(datamat,datamat[i,:].T)

In [65]:
k[0:3,0:3]

matrix([[ 16.45930283,  15.74944568,  23.62676274],
        [ 15.74944568,  15.64899582,  18.75800936],
        [ 23.62676274,  18.75800936,  59.52179808]])

In [69]:
k1 == k

matrix([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ..., 
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]], dtype=bool)

In [67]:
k_ = k*0

In [106]:
k2 = k3 = k

In [141]:
for i in range(m):
    
    for j in range(m):
        
        k2[j,i] = (datamat[j,:] - datamat[i,:]) * (datamat[j,:] - datamat[i,:]).T 
        

In [142]:
k2[0:3,0:3]

matrix([[  0.        ,   0.60940729,  28.72757543],
        [  0.60940729,   0.        ,  37.65477518],
        [ 28.72757543,  37.65477518,   0.        ]])

In [109]:
k2 = np.exp(k2/(-1*1.3**2))

In [110]:
k2[0:3,0:3]

matrix([[  1.00000000e+00,   6.97260616e-01,   4.14588138e-08],
        [  6.97260616e-01,   1.00000000e+00,   2.10627054e-10],
        [  4.14588138e-08,   2.10627054e-10,   1.00000000e+00]])

In [111]:
datamat1 = np.tile(datamat.T,(100,1))

In [112]:
datamat1.shape

(200, 100)

In [113]:
datamat.shape

(100, 2)

In [114]:
datamat[:3]

matrix([[ 3.542485,  1.977398],
        [ 3.018896,  2.556416],
        [ 7.55151 , -1.58003 ]])

In [115]:
datamat2 = datamat1

In [124]:
datamat2 = datamat.ravel('f')

In [127]:
datamat2 = np.tile(datamat2,(100,1))

In [129]:
datamat2.shape


(100, 200)

In [136]:
datamat1 = np.tile(datamat,(1,100))

In [146]:
datamat1.shape

(100, 200)

In [148]:
(datamat1 - datamat2).shape

(100, 200)

In [143]:
k3 =  np.dot((datamat1 - datamat2),(datamat1 - datamat2).T)

In [144]:
k3[:3,:3]

matrix([[ 2408.2844387 ,  2331.70944903,  2961.63406638],
        [ 2331.70944903,  2316.07518788,  2469.16945306],
        [ 2961.63406638,  2469.16945306,  6387.74123663]])

In [ ]:
dat